language: generic 
sudo : required
services:
  - docker

  before_install:
    -docker build -t nicomdt/docker-react -f Dockerfile.dev .

  script:
  - docker run -e CI=true nicomdt/docker-react npm run test -- --coverage